Reddit/config/routes.rb
Rails.application.routes.draw do
  root to: "subs#index"
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs do
    resources :posts, only: [:create]
  end
    resources :posts, except: [:create, :index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Reddit/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Reddit/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string
#  url        :string
#  content    :text
#  sub_id     :integer
#  author_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, presence: true

  belongs_to :sub

  belongs_to :author,
    foreign_key: :author_id,
    class_name: :User

  has_many :postsubs,
    foreign_key: :post_id,
    class_name: :PostSub

  has_many :cross_subs,
    through: :postsubs,
    source: :sub
end

Reddit/app/models/post_sub.rb
class PostSub < ApplicationRecord
  belongs_to :post
  belongs_to :sub
end

Reddit/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string
#  description  :text
#  moderator_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, presence: true, uniqueness: true

  belongs_to :moderator,
    foreign_key: :moderator_id,
    class_name: :User

  has_many :posts

  has_many :post_subs

  has_many :cross_posts,
    through: :post_subs,
    source: :post
end

Reddit/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string
#  password_digest :string
#  session_token   :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :username, :password_digest, presence: true

  after_initialize :ensure_session_token
  attr_reader :password

  has_many :posts

  has_many :moderated_subs,
    foreign_key: :moderator_id,
    class_name: :Sub

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_token
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user && user.valid_password?(password)
    user
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

end

Reddit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def log_in(user)
    session[:session_token] = user.reset_token
  end

  def log_out
    current_user.try(:reset_token)
    session[:session_token] = nil
  end

  def require_log_in
    redirect_to new_session_url unless logged_in?
  end
end

Reddit/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_log_in

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.sub_id = params[:sub_id]
    @post.author_id = current_user.id

    if @post.save
      params[:sub][:cross_posts].each do |sub|
        PostSub.create!(post: @post, sub: Sub.find(sub.to_i))
      end
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])

    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to sub_url(@post.sub)
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, :cross_subs)
  end
end

Reddit/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user
      log_in(user)
      redirect_to subs_url
    else
      flash.now[:errors] = ['Invalid username or password']
      render :new
    end
  end

  def destroy
    log_out
    redirect_to new_session_url
  end
end

Reddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_log_in
  def new
    @sub = Sub.new
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def create
    @sub = Sub.new(sub_params)

    if @sub.save
      redirect_to subs_url
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def update
    @sub = current_user.moderated_subs.find(params[:id])

    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def destroy
    @sub = Sub.find(params[:id])
    if @sub.moderator == current_user
      @sub.destroy
      redirect_to subs_url
    end
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

Reddit/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

Reddit/app/helpers/application_helper.rb
module ApplicationHelper
end

Reddit/app/helpers/posts_helper.rb
module PostsHelper
end

Reddit/app/helpers/sessions_helper.rb
module SessionsHelper
end

Reddit/app/helpers/subs_helper.rb
module SubsHelper
end

Reddit/app/helpers/users_helper.rb
module UsersHelper
end

Reddit/app/views/layouts/_errors.html.erb
<% flash[:errors].join("<br>").html_safe if flash[:errors] %>

Reddit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>


    <% if flash[:errors] %>
      <% flash[:errors].each do |err| %>
        <%= err %>
      <% end %>
    <% end %>


    <% if logged_in? %>
      <label>
        <%= current_user.username %>
      </label>
      <%= button_to "Sign Out", session_url, method: :delete %>
      <%= link_to 'All Subs', subs_url %>
    <% else %>
      <%= link_to 'Sign Up', new_user_url %>
      <%= link_to 'Sign In', new_session_url %>
    <% end %>



    <%= yield %>
  </body>
</html>

Reddit/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

Reddit/app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

Reddit/app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

Reddit/app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

Reddit/app/views/posts/show.html.erb
<%= link_to @post.sub.title, sub_url(@post.sub) %>
<h1><%= @post.title %></h1>
<%= @post.author.username %>

<ul>
  <li> <%= @post.url %> </li>
  <li> <%= @post.content %> </li>


</ul>

Reddit/app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

Reddit/app/views/subs/create.html.erb
<h1>Subs#create</h1>
<p>Find me in app/views/subs/create.html.erb</p>

Reddit/app/views/subs/destroy.html.erb
<h1>Subs#destroy</h1>
<p>Find me in app/views/subs/destroy.html.erb</p>

Reddit/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<form action= "<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="patch">

  <label>
    Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>

  <label>
    Description
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label>

  <button>Update Sub</button>

</form>

Reddit/app/views/subs/index.html.erb
<h1>All Subs</h1>
<% Sub.all.each do |sub| %>
  <li> <%= link_to sub.title, sub_url(sub) %> </li>
<% end %>

Reddit/app/views/subs/new.html.erb
<h1>Subs#new</h1>
<p>Find me in app/views/subs/new.html.erb</p>

Reddit/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<p><%= @sub.description %></p>
<% if @sub.moderator_id == current_user.id %>
  <%= button_to "Edit Sub", edit_sub_url, method: :get %>
<% end %>

<br><ul>
  <% @sub.posts.each do |post| %>
    <li><%= link_to post.title, post_url(post) %></li> 
  <% end %>
  <% @sub.cross_posts.each do |xpost| %>
    <li><%= link_to xpost.title, post_url(xpost) %></li>
  <% end %>
</ul><br>

<form action="<%= sub_posts_url(@sub) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label> Title:
    <input type="text" name="post[title]" value="">
  </label><br>

  <label>URL:
    <input type="text" name="post[url]" value="">
  </label><br>

  <label>Content:
    <input type="text" name="post[content]" value="">
  </label><br>

  <label>Cross Post:
    <% Sub.all.each do |sub| %>
      <label><%= sub.title %>
        <input type="checkbox" name="sub[cross_posts][]" value="<%= sub.id %>">
      </label>
    <% end %>
  </label><br>

  <button>Submit Post</button>
</form>

Reddit/app/views/subs/update.html.erb
<h1>Subs#update</h1>
<p>Find me in app/views/subs/update.html.erb</p>

Reddit/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

Reddit/app/views/users/new.html.erb
<h1>Create Account</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>
    Username
    <input type="text" name="user[username]" value="">
  </label>
  <br>
  <label>
    Password
    <input type="password" name="user[password]" value="">
  </label>
  <br>
  <button>Sign Up Butthole</button>
</form>